### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by mingyee2** [lmmentel/mendeleev#35]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.8/site-packages/mendeleev/ion.py", line 119, in __getattr__
    raise AttributeError(
AttributeError: 'econf' is not **na** attribute of 'Ion'
```

**Comment by lmmentel** [comment]
Thanks for taking the time to submit an issue @mingyee2 :+1:
